# Index, slicing and iterating

In [46]:
import numpy as np

Indexing

In [47]:
a = np.array([4, 1, 9, 6, 7])
print('Usual python list indexing', a[2])

Usual python list indexing 9


In [48]:
a = np.array([[4, 1, 9], [6, 7, 10]])
print('Multilist indexing', a[0, 2])

Multilist indexing 9


In [49]:
# Here we defined an array using the previous array data
np.array([a[0, 2], a[1, 2]])

array([ 9, 10])

In [50]:
# And here we have the same output like in the previous example
# because by this way these two lists "zips" the values
print(a[[0, 1], [2, 2]])

[ 9 10]


Boolean indexing

In [51]:
# Like in pandas we can check a boolean operator and get a boolean array with the
# validation results.
print(a > 3)

[[ True False  True]
 [ True  True  True]]


In [52]:
# And then filter our array using a "mask"
print(a)
print(a[a > 3])
# Notice that this operation returns an array

[[ 4  1  9]
 [ 6  7 10]]
[ 4  9  6  7 10]


Slicing

In [53]:
# Creating an array based on a original array.
# Its pretty similiar with usual python slicing
a = np.arange(0, 6, 1)
a

array([0, 1, 2, 3, 4, 5])

In [54]:
a[0:3]

array([0, 1, 2])

In [55]:
# Now with multidimentional arrays
a = np.arange(1, 13, 1).reshape(3, 4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [56]:
# Here we get the first two rows
a[:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [57]:
# And here we get three rows and in each one
# we get the [1, 3) values.
a[:3, 1:3]

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

In [58]:
reference_array = a[:3, 1:3]
reference_array

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

In [59]:
# Here we can see that slicing return a value as reference
# so when we edit a value in the reference object the 
# original object is beign modified too.
print('before edit \n', reference_array)
reference_array[0, 0] = 75
print('after edit \n', reference_array)
print('original array \n', a)


before edit 
 [[ 2  3]
 [ 6  7]
 [10 11]]
after edit 
 [[75  3]
 [ 6  7]
 [10 11]]
original array 
 [[ 1 75  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
